// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/storage/note_index.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 7739484054000759531),
    name: 'NoteIndexEntry',
    lastPropertyId: const obx_int.IdUid(10, 3644225320320819579),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 845074007457441571),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 2728725345681016970),
        name: 'noteId',
        type: 9,
        flags: 2080,
        indexId: const obx_int.IdUid(1, 760666945196795956),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1706667854024407074),
        name: 'category',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8329104469740971156),
        name: 'customCategory',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6941932637366351638),
        name: 'confidence',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 6009269819717551858),
        name: 'source',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 3472995820159332778),
        name: 'createdAt',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 842752477694609508),
        name: 'updatedAt',
        type: 12,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7138177267031371405),
        name: 'tags',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3644225320320819579),
        name: 'searchContent',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 7739484054000759531),
    lastIndexId: const obx_int.IdUid(1, 760666945196795956),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    NoteIndexEntry: obx_int.EntityDefinition<NoteIndexEntry>(
      model: _entities[0],
      toOneRelations: (NoteIndexEntry object) => [],
      toManyRelations: (NoteIndexEntry object) => {},
      getId: (NoteIndexEntry object) => object.obxId,
      setId: (NoteIndexEntry object, int id) {
        object.obxId = id;
      },
      objectToFB: (NoteIndexEntry object, fb.Builder fbb) {
        final noteIdOffset = fbb.writeString(object.noteId);
        final categoryOffset = fbb.writeString(object.category);
        final customCategoryOffset = object.customCategory == null
            ? null
            : fbb.writeString(object.customCategory!);
        final sourceOffset = fbb.writeString(object.source);
        final tagsOffset = fbb.writeString(object.tags);
        final searchContentOffset = fbb.writeString(object.searchContent);
        fbb.startTable(11);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, noteIdOffset);
        fbb.addOffset(2, categoryOffset);
        fbb.addOffset(3, customCategoryOffset);
        fbb.addFloat64(4, object.confidence);
        fbb.addOffset(5, sourceOffset);
        fbb.addInt64(6, object.createdAt.microsecondsSinceEpoch * 1000);
        fbb.addInt64(
          7,
          object.updatedAt == null
              ? null
              : object.updatedAt!.microsecondsSinceEpoch * 1000,
        );
        fbb.addOffset(8, tagsOffset);
        fbb.addOffset(9, searchContentOffset);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final updatedAtValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final noteIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final categoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final customCategoryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final confidenceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final sourceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final createdAtParam = DateTime.fromMicrosecondsSinceEpoch(
          (const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0) / 1000)
              .round(),
        );
        final updatedAtParam = updatedAtValue == null
            ? null
            : DateTime.fromMicrosecondsSinceEpoch(
                (updatedAtValue / 1000).round(),
              );
        final tagsParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 20, '');
        final searchContentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 22, '');
        final object = NoteIndexEntry(
          noteId: noteIdParam,
          category: categoryParam,
          customCategory: customCategoryParam,
          confidence: confidenceParam,
          source: sourceParam,
          createdAt: createdAtParam,
          updatedAt: updatedAtParam,
          tags: tagsParam,
          searchContent: searchContentParam,
        )..obxId = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [NoteIndexEntry] entity fields to define ObjectBox queries.
class NoteIndexEntry_ {
  /// See [NoteIndexEntry.obxId].
  static final obxId = obx.QueryIntegerProperty<NoteIndexEntry>(
    _entities[0].properties[0],
  );

  /// See [NoteIndexEntry.noteId].
  static final noteId = obx.QueryStringProperty<NoteIndexEntry>(
    _entities[0].properties[1],
  );

  /// See [NoteIndexEntry.category].
  static final category = obx.QueryStringProperty<NoteIndexEntry>(
    _entities[0].properties[2],
  );

  /// See [NoteIndexEntry.customCategory].
  static final customCategory = obx.QueryStringProperty<NoteIndexEntry>(
    _entities[0].properties[3],
  );

  /// See [NoteIndexEntry.confidence].
  static final confidence = obx.QueryDoubleProperty<NoteIndexEntry>(
    _entities[0].properties[4],
  );

  /// See [NoteIndexEntry.source].
  static final source = obx.QueryStringProperty<NoteIndexEntry>(
    _entities[0].properties[5],
  );

  /// See [NoteIndexEntry.createdAt].
  static final createdAt = obx.QueryDateNanoProperty<NoteIndexEntry>(
    _entities[0].properties[6],
  );

  /// See [NoteIndexEntry.updatedAt].
  static final updatedAt = obx.QueryDateNanoProperty<NoteIndexEntry>(
    _entities[0].properties[7],
  );

  /// See [NoteIndexEntry.tags].
  static final tags = obx.QueryStringProperty<NoteIndexEntry>(
    _entities[0].properties[8],
  );

  /// See [NoteIndexEntry.searchContent].
  static final searchContent = obx.QueryStringProperty<NoteIndexEntry>(
    _entities[0].properties[9],
  );
}
